services:
  petclinic-with-react:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - "5173:5173"
    volumes:
      - ./node_modules:/usr/src/app/node_modules
    user: "node"
    networks:
      - petclinic-network

networks:
  petclinic-network:
    external: true
