services:

  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - "./conf.d:/etc/postgresql/conf.d:ro"
    networks:
      - petclinic-network

  petclinic-spring-boot:
    build:
      context: .
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - petclinic-network
    depends_on:
      - postgres

networks:
  petclinic-network:
    external: true
